name: Continuous Deployment

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  staging_deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2 
        continue-on-error: true
      - name: Build and push docker image
        run: |
          sudo echo '127.0.0.1  kubernetes' >> /etc/hosts
          export NEW_TAG="v$(git rev-parse --short HEAD)";
          echo "New tag: $NEW_TAG";
          pip3 install ec2instanceconnectcli==1.0.2
          python3 deployment/staging/buildspec.py
        env:
          EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
          LOCAL_PORT: ${{ secrets.LOCAL_PORT }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          EKS_KUBECTL_ROLE: ${{ secrets.EKS_KUBECTL_ROLE }}
          ROLE_SESSION_NAME: ${{ secrets.ROLE_SESSION_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
