name: Continuous Deployment

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  staging_deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2 
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build and push docker image
        run: |
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
          export NEW_TAG="v$(git rev-parse --short HEAD)";
          echo "New tag: $NEW_TAG";
          apt-get update
          apt-get install mssh
          python deployment/staging/buildspec.py
        env:
          EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
          LOCAL_PORT: ${{ secrets.LOCAL_PORT }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          EKS_KUBECTL_ROLE: ${{ secrets.EKS_KUBECTL_ROLE }}
          ROLE_SESSION_NAME: ${{ secrets.ROLE_SESSION_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Staging Deploy Status - ${{ job.status }}
          SLACK_TITLE: Deploy OLD QBO APP to Staging
          SLACK_ICON_EMOJI: ":pepeok:"
          SLACK_USERNAME: QBO
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_FOOTER: ''