name: Continuous Deployment

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  staging_deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2 
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build and push docker image
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install 
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
          export NEW_TAG="v$(git rev-parse --short HEAD)";
          echo "New tag: $NEW_TAG";
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fyle_qbo-app:$NEW_TAG .
          echo "Pushing Docker Image to Docker Hub";
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fyle_qbo-app:$NEW_TAG
          echo "NEW_TAG=v$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          pip3 install mssh
          python deployment/staging/buildspec.py
        env:
          EKS_CLUSTER_NAME: ${{ secrets.DOCKERHUB_USERNAME }}
          AWS_REGION: ${{ secrets.DOCKERHUB_USERNAME }}
          LOCAL_HOST: ${{ secrets.DOCKERHUB_USERNAME }}
          LOCAL_PORT: ${{ secrets.DOCKERHUB_USERNAME }}
          REMOTE_PORT: ${{ secrets.DOCKERHUB_USERNAME }}
          EKS_KUBECTL_ROLE: ${{ secrets.DOCKERHUB_USERNAME }}
          ROLE_SESSION_NAME: ${{ secrets.DOCKERHUB_USERNAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCKERHUB_USERNAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCKERHUB_USERNAME }} 
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Staging Deploy Status - ${{ job.status }}
          SLACK_TITLE: Deploy OLD QBO APP to Staging
          SLACK_ICON_EMOJI: ":pepeok:"
          SLACK_USERNAME: QBO
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_FOOTER: ''